### ISSUE TITLE
Support other actions on attachables

### ISSUE THREAD

**Issue by atty-stripe** [minimul/qbo_api#103]
Looks like this package only supports uploading attachments for now. Would be great to support the other endpoints: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/attachable.

In particular, supporting deleting attachments would be very useful for our use case.

**Comment by minimul** [comment]
I agree these would be worthy additions. Can you take a crack at it?

**Comment by atty-stripe** [comment]
Not at the moment, but can take a look if no one else picks it up in a few weeks. Thanks for responding!
