### ISSUE TITLE
Is the "OAuth2: Spin up an example" current?

### ISSUE THREAD

**Issue by jwgrenning** [minimul/qbo_api#107]
"Create a new Company (from the manage sandboxes page) Don't use it for anything else besides testing this"

I'm getting stuck on this step.  The "manage sandboxes page" does not go to a "manage sandboxes page".

thanks!

**Comment by minimul** [comment]
Since Inuit regularly tweaks stuff, probably not, but it would great if when you get unstuck you could contribute back what you've learned.

**Comment by minimul** [comment]
FWIW: In branch [2_0_0](https://github.com/minimul/qbo_api/tree/2_0_0) I verified that the example app is working.
This branch will soon be merged into master and released as 2.0.0.
