### ISSUE TITLE
Remove dependency on faraday_middleware

### ISSUE THREAD

**Issue by wheresrobert** [minimul/qbo_api#113]
`faraday_middleware` is deprecated. 

[https://github.com/lostisland/faraday_middleware](https://github.com/lostisland/faraday_middleware)

`qbo_api` is the only gem in my project that depends on `faraday_middleware`, which in turn, prevents upgrading of faraday itself.

**Comment by minimul** [comment]
Thanks for the heads up. Taking a look.

**Comment by minimul** [comment]
Notes:

The `qbo_api` gem is utilizing two aspects of the`faraday_middleware` gem:

1. A homebrew middleware "RaiseHttpException" module that inherits from Faraday::Middleware;
2. and the **OAuth2** middleware included in the `faraday_middleware` gem.

If anyone would like to tackle these two?

**Comment by minimul** [comment]
Closing. Version 3.0.0 removes `faraday_middleware` dependency.
