### ISSUE TITLE
Cannot delete a journalentry

### ISSUE THREAD

**Issue by map7** [minimul/qbo_api#132]
When using 

    @qbo_api.delete(:journalentry, id: id)

I get the following error

Error: test_journal_create(ReportCraftTest): QboApi::NotImplementedError: Delete is only for transaction entities. Use .deactivate instead

But from what I've read in the code it should pass, but the problem I think is the following line doesn't match properly.
https://github.com/minimul/qbo_api/blob/f06ffbe5ed98aae28c5e0eca7116ffd275bfb904/lib/qbo_api/entity.rb#L37

(ruby) singular(entity)
"Journalentry"

This doesn't find it in the accepted list because the accepted list only includes JournalEntry.

**Comment by map7** [comment]
Workaround;
`@qbo_api.delete(:journal_entry, id: id)`

Maybe this should be added as an example to the docs as it's inconsistent with how we call :journalentry for other things such as
`@qbo_api.create(:journalentry, payload: journal)`

**Comment by minimul** [comment]
The workaround example to me is the proper style considering that QuickBooks has it at as `JournalEntry` in the API (even though to query the entities they are treated as case-insensitive).

But you're right about the inconsistency.

Yes, something in the docs would be best way to go.

**Comment by map7** [comment]
#133
