### ISSUE TITLE
Ampersand in QB query breaks OAuth

### ISSUE THREAD

**Issue by martinsabo** [minimul/qbo_api#20]
Hi,
first of all, thank you for your work on this great gem.

I have run recently into weird problems where some query api requests failing with auth exception. The core of the problem is actually known to you according to this article: http://minimul.com/escaping-an-ampersand-within-an-oauth-request.html was 

Current implementation of the request method does a URI encode on whole path and the ampersand character is not escaped/encoded for obvious reason. So at least for query requests this is not ideal approach.

I have solved this issue only with some simple and not very elegant overrides for now. Something like:

```ruby
class FixedQboApi < QboApi
        def request(method, path:, entity: nil, payload: nil, url_encode: true)
          raw_response = connection.send(method) do |req|
            case method
              when :get, :delete
                p =  url_encode ? URI.encode(path) : path
                req.url p
              when :post, :put
                req.url add_request_id_to(path)
                req.body = JSON.generate(payload)
            end
          end
          response(raw_response, entity: entity)
        end

        def query(query)
          path = "#{realm_id}/query?query=#{CGI.escape(query)}"
          entity = extract_entity_from_query(query, to_sym: true)
          request(:get, entity: entity, path: path, url_encode: false)
        end
end
```
 The url encoding in the request method is optional in the fixed class and query method escapes only parameter not whole path.

Regards,

Martin

**Comment by minimul** [comment]
Oh yeah....

Ok, I will get the fixed pretty soon. Thanks so much for reporting it.

**Comment by minimul** [comment]
Your approach is correct and that is basically what I put into [the PR](https://github.com/minimul/qbo_api/pull/21)

This fix is released so you may delete the override code and then`bundle update qbo_api`.

Thanks @martinsabo
