### ISSUE TITLE
SKU column in QBO API minor version 4

### ISSUE THREAD

**Issue by afcw** [minimul/qbo_api#22]
SKU column is finally available via QBO API in the updated minor version 4.
https://intuitdeveloper.lc.intuit.com/questions/1421191-is-show-sku-column-available-via-api

Would be great if the gem can be updated to the new QBO API. Thanks!

**Comment by minimul** [comment]
Update: I am going to look at this starting this Friday or this coming Monday.

**Comment by minimul** [comment]
This is in master but not yet released in a Gem version.

If you could run it for your needs and report back that
would be swell.

Please see README for usage.

**Comment by afcw** [comment]
Christian,
I just checked and am able to query by the SKU column. 

response = qbo_api.query(%{SELECT * From Item Where Sku = '12345'})

However, the resulting response lacked SKU as a parameter. I even queried by Id,
response = qbo_api.get(:item, "20")
and still no SKU in the response:
 "Name"=>"Hose", 
"Description"=>"hose is for the sprinkler system.", 
"Active"=>true, "SubItem"=>true, 
"ParentRef"=>    {"value"=>"17", "name"=>"Sprinkler System:Sprinkler Pipes"}, 
"Level"=>2, 
"FullyQualifiedName"=>"Sprinkler System:Sprinkler Pipes:Hose", 
"Taxable"=>true, 
"UnitPrice"=>2, 
"Type"=>"Inventory", 
"IncomeAccountRef"=>{"value"=>"79", "name"=>"Sales of Product Income"}, 
"PurchaseDesc"=>"Green Hose", 
"PurchaseCost"=>1, 
"ExpenseAccountRef"=>{"value"=>"80", "name"=>"Cost of Goods Sold"}, 
"AssetAccountRef"=>{"value"=>"81", "name"=>"Inventory Asset"}, 
"TrackQtyOnHand"=>true, 
"InvStartDate"=>"2012-11-01", 
"domain"=>"QBO", 
"sparse"=>false, 
"Id"=>"20", 
"SyncToken"=>"2", 
"MetaData"=>{"CreateTime"=>"2016-11-19T16:27:11-08:00", 
"LastUpdatedTime"=>"2016-11-19T17:02:10-08:00"}}
I updated my gemfile to reference the qbo_api git repository, 
gem 'qbo_api', :git => 'https://github.com/minimul/qbo_api.git'
and then ran bundle update qbo_api
Thanks,Wanda

**Comment by minimul** [comment]
Please see the README for minorversion usage.

On Fri, Dec 02, 2016 at 02:36 AM, Wanda <notifications@github.com> wrote:

> from: Wanda <notifications@github.com>
> date: Thu, Dec 01 11:36 PM -08:00 2016
> to: minimul/qbo_api <qbo_api@noreply.github.com>
> cc: Christian Pelczarski <zarski@gmail.com>, Comment <comment@noreply.github.com>
> reply-to: minimul/qbo_api <reply@reply.github.com>
> subject: Re: [minimul/qbo_api] SKU column in QBO API minor version 4 (#22)
> 
> Christian,
> I just checked and am able to query by the SKU column. 
> 
> response = qbo_api.query(%{SELECT * From Item Where Sku = '12345'})
> 
> However, the resulting response lacked SKU as a parameter. I even queried by Id,
> response = qbo_api.get(:item, "20")
> and still no SKU in the response:
>  "Name"=>"Hose", 
> "Description"=>"hose is for the sprinkler system.", 
> "Active"=>true, "SubItem"=>true, 
> "ParentRef"=>    {"value"=>"17", "name"=>"Sprinkler System:Sprinkler Pipes"}, 
> "Level"=>2, 
> "FullyQualifiedName"=>"Sprinkler System:Sprinkler Pipes:Hose", 
> "Taxable"=>true, 
> "UnitPrice"=>2, 
> "Type"=>"Inventory", 
> "IncomeAccountRef"=>{"value"=>"79", "name"=>"Sales of Product Income"}, 
> "PurchaseDesc"=>"Green Hose", 
> "PurchaseCost"=>1, 
> "ExpenseAccountRef"=>{"value"=>"80", "name"=>"Cost of Goods Sold"}, 
> "AssetAccountRef"=>{"value"=>"81", "name"=>"Inventory Asset"}, 
> "TrackQtyOnHand"=>true, 
> "InvStartDate"=>"2012-11-01", 
> "domain"=>"QBO", 
> "sparse"=>false, 
> "Id"=>"20", 
> "SyncToken"=>"2", 
> "MetaData"=>{"CreateTime"=>"2016-11-19T16:27:11-08:00", 
> "LastUpdatedTime"=>"2016-11-19T17:02:10-08:00"}}
> I updated my gemfile to reference the qbo_api git repository, 
> gem 'qbo_api', :git => 'https://github.com/minimul/qbo_api.git'
> and then ran bundle update qbo_api
> Thanks,Wanda
> 
>       From: Christian Pelczarski <notifications@github.com>
>  To: minimul/qbo_api <qbo_api@noreply.github.com> 
> Cc: Wanda <mail.wandac@yahoo.com>; Author <author@noreply.github.com>
>  Sent: Thursday, December 1, 2016 7:12 AM
>  Subject: Re: [minimul/qbo_api] SKU column in QBO API minor version 4 (#22)
>    
> This is in master but not yet released in a Gem version.If you could run it for your needs and report back that
> would be swell.Please see README for usage.—
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.  
> 
>    
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/minimul/qbo_api/issues/22#issuecomment-264392470


Regards — Christian

**Comment by afcw** [comment]
Sorry, I misunderstood the README remark earlier. (The README file for minor-ver and master looked the same.) But upon reading more closely, figured out what you meant. I did as instructed and was successful in extracting Sku from the parameters. So, it works for me! Thanks again and hope you had a great Thanksgiving!

**Comment by minimul** [comment]
Minor version support has been released in 1.4.0
