### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by graudeejs** [minimul/qbo_api#28]
> As of July 17, 2017, new or existing developers with no previous apps must implement OAuth 2.0.

https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app#/OAuth_Community_Resources

**Comment by minimul** [comment]
Yup. I'll be working on this soon (this week possibly). 

If you can jump in that'll be great too.

**Comment by graudeejs** [comment]
Well, I managed to create invoice using qbo_api with oauth2.

Here's my commit: https://github.com/graudeejs/qbo_api/commit/845bc87e239a5e96f50d315c52d3b7962ff423d3

Example app is broken!
I fixed tests, however you should inspect this more closely.

If you wan't I can make a pull request.

**Comment by minimul** [comment]
Thanks.

I have a branch in progress that'll have the example app working as well.

**Comment by graudeejs** [comment]
@minimul Do you want me to create pull request?

**Comment by minimul** [comment]
No but thank you. I have the commit almost ready.

**Comment by minimul** [comment]
Closed in #29
