### ISSUE TITLE
Issue querying all records

### ISSUE THREAD

**Issue by rdrop** [minimul/qbo_api#32]
When running:

`qbo_api.all(:customers).each do |c|`
    `     p "#{c['Id']} #{c['DisplayName']}"`
` end`

The following error is returned in the console:

`LocalJumpError: no block given (yield)`

**Comment by minimul** [comment]
I'm not able to reproduce.

**Comment by ntippie** [comment]
You should pass the block directly to the #all method, not to #each:

```ruby
qbo_api.all(:customers) do |c|
  p "#{c['Id']} #{c['DisplayName']}"
end
```

**Comment by minimul** [comment]
Yes, but `.each` does work as well. Closing.
