### ISSUE TITLE
Error 22 Authentication required on disconnect with OAuth2

### ISSUE THREAD

**Issue by piotrbryniarski** [minimul/qbo_api#38]
When trying to disconnect my QboApi client I get:
```
client.disconnect
{"ErrorMessage"=>"Authentication required", "ErrorCode"=>22, "ServerTime"=>"/Date(1511453624425)/"}
```
The other functionalities, like `client.all(:company_info).entries.to_a` work normally. What is more I am almost sure `disconnect` worked before too. What can I do to have this client disconnected?

**Comment by bf4** [comment]
I've never used disconnect.  I thought it was part of the old api.

**Comment by minimul** [comment]
@piotrbryniarski I don't have a client on OAuth2 yet. Can you continue to try to figure this out?

@bf4 For a QuickBooks App store entry you do need a working disconnect.

**Comment by minimul** [comment]
Disconnect is a v3 API call and should work within both OAuth1 & 2. Reopen if needed.

**Comment by bf4** [comment]
@piotrbryniarski I split up the api methods in https://github.com/minimul/qbo_api/pull/76/files which may help clarify this. They're still mixed together in the Ruby object, but now you can see logical lines
