### ISSUE TITLE
Instructions for getting started with the example app no longer work

### ISSUE THREAD

**Issue by JohnSmall** [minimul/qbo_api#46]
I think the instructions for starting the example app haven't kept up to date with the changes in QBO. When I follow the instruction in this link [Part 1](http://minimul.com/getting-started-with-the-modern-ruby-quickbooks-online-client-qbo_api-part-1.html) they refer to Oauth Consumer Key, and Oauth Consumer Secret. But the latest QBO app page only has 'Client ID' and 'Client Secret'

I tried using the values of Client ID in place of Oauth Consumer Key, and Client Secret in Oauth Consumer Secret. But that gave an error 
<img width="764" alt="screen shot 2018-01-04 at 17 03 36" src="https://user-images.githubusercontent.com/38699/34577321-aa73c9f6-f178-11e7-863a-31cea1b20158.png">

Also the instructions show only a button on the home page of the example app. But in the actual app there's a link to Oauth2 connect page. But if I follow that link then I get this error

<img width="993" alt="screen shot 2018-01-04 at 17 59 31" src="https://user-images.githubusercontent.com/38699/34577483-29e5a18c-f179-11e7-8e3d-59e298fec03d.png">

So, next try, read the code. I see in the code 

     CLIENT_ID = ENV['QBO_API_CLIENT_ID']
     CLIENT_SECRET = ENV['QBO_API_CLIENT_SECRET']

Ahhh! This is not mentioned in the instructions.

So in my .env file I added QBO_API_CLIENT_ID and QBO_API_CLIENT_SECRET using the values for Client ID, and Client Secret and removed Oauth Consumer Key & etc 

Then ...

On the home page of the app, the button fails with 

<img width="756" alt="screen shot 2018-01-04 at 18 16 16" src="https://user-images.githubusercontent.com/38699/34578064-809f8018-f17b-11e7-83c6-f8d751623bfd.png">

But the link to Oauth2 connect page doesn't get an error! This time I see another page with a single button on it. Clicking the button then gives this error

<img width="1437" alt="screen shot 2018-01-04 at 18 18 57" src="https://user-images.githubusercontent.com/38699/34578210-fb9e9a2e-f17b-11e7-8cec-11be73a7d3ac.png">

Which is progress of a sort, but obviously the instructions bare no relation to the new reality and so I completely abandoned them. I'm on my own with the source code and error messages to work through. So...

 Reading the source I see 

     `client = Rack::OAuth2::Client.new(
      identifier: CLIENT_ID,
      secret: CLIENT_SECRET,
      redirect_uri: "http://localhost:#{PORT}/oauth2-redirect",
      authorization_endpoint: "https://appcenter.intuit.com/connect/oauth2",
      token_endpoint: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
    )
`

Ahh! so I have to set up the redirect URL in QBO. Once I've done that and I restart then I do get redirected to the correct login sequence and can connect the test app to a sandbox. and I get an access token and a refresh token.

Conclusion. The code works but the instructions are completely out of date.

**Comment by DAMisener** [comment]
Thanks for this... 

I've been having similar discrepancies based on the supplied example (and YouTube video)

What's even worse is my end goal is a *simple* command line utility to export AR invoice and reformat it for posting into another legacy accounting system.  OAUTH2 with QBO redirect is *messing with my mind*. :-(

**Comment by minimul** [comment]
Thanks @JohnSmall for posting that. Glad it is already helping. If you can fix up the README that would great too.

**Comment by JohnSmall** [comment]
Ok, I think the most important part of the fix in the README would be to change 

    Part 1: Learn how to spin up the example app.

to 
     
    Part: Learn how to spin up the example app with OAuth (link to the OAuth section) or If you signed 
     up for a Intuit developer account after July 17th, 2017 follow this example (link to OAuth 2 section)

After spending ages working out how to get the example to work using the instructions for OAuth, linked at the top of the page, I found the complete instructions for OAuth2 at the bottom of the page.

What do you think? I'll fork, change and make a PR if that's how you'd like it.

**Comment by JohnSmall** [comment]
Question following on from that. The specs require setting Consumer Key and Consumer Secret, which aren't available if you've got a recent QBO account and can't use OAuth. So how do I run the specs? I'm about to find out.

**Comment by minimul** [comment]
re: README. Yes, send in a PR.

Yeah, specs aren't OAuth2 ready but it shouldn't be too much work to support them.

Something in `spec/support/credentials.rb` => `creds()` to use the `oauth2_creds()` hash instead based on what vars you have set in the `.env` file.

That'll be great if you could work on that too.

**Comment by JohnSmall** [comment]
Yes, I can see the issue with specs and OAuth2. I'll do that as well while I'm at it. Separate PRs though.
