### ISSUE TITLE
Updates are not passing Id correctly

### ISSUE THREAD

**Issue by canavese** [minimul/qbo_api#5]
set_update sets the Id in the outgoing request as resp['Id'], but resp is coming back with a hash with the entity name as the key and a hash as the value.  

{"SalesReceipt"=>{"domain"=>"QBO", "sparse"=>false, "Id"=>"15829", ...}}

It seems like you intend for those responses to be one level down.  Or am I missing something?

Thanks!

**Comment by minimul** [comment]
Taking a look.

**Comment by minimul** [comment]
In my project I have not yet used "multiword" entities so embarrassingly this was broken but fixed now
in master and new gem push as well, `1.1.0`, Thanks.
