### ISSUE TITLE
Need to setup Travis

### ISSUE THREAD

**Issue by minimul** [minimul/qbo_api#53]
Had a couple bad releases today. 

1 would have been stopped by having a CI.

**Comment by bf4** [comment]
@minimul http://travis-ci.org/minimul/qbo_api just says it's not an active repo.. Repo already has a .travis.yml

**Comment by minimul** [comment]
Right, I needed to fix something around the VCR cassettes or maybe it was something with .env vars.

**Comment by bf4** [comment]
If you enable it, I can make a message-only PR to force a build

**Comment by minimul** [comment]
OK, I'll get to this soon.

**Comment by minimul** [comment]
Closed. https://github.com/minimul/qbo_api/pull/64
