### ISSUE TITLE
Minor version as instance variable

### ISSUE THREAD

**Issue by ntippie** [minimul/qbo_api#56]
I ran into a scenario recently where I needed to use a lesser minor version for specific requests. However, the current implementation was not thread-safe to be changing `QboApi.minor_version` between requests. I decided to add an instance variable for `#minor_version`, as you can see [on my fork](https://github.com/minimul/qbo_api/compare/master...ntippie:master).

Would you like me to submit a PR?

**Comment by minimul** [comment]
Yes, please submit.
