### ISSUE TITLE
Time serialization

### ISSUE THREAD

**Issue by ntippie** [minimul/qbo_api#58]
Some objects that use datetimes (Time or DateTime classes in Ruby) are not encoded into ISO 8601 as required by the QBO API. This causes a QboApi::BadRequest error to be raised.

```ruby
qbo_api.create(:time_activity, payload: 
    {
        NameOf: 'Employee', 
        EmployeeRef: {value: 1}, 
        StartTime: Time.parse('2018-01-24T09:10:18+00:00'), 
        EndTime: Time.parse('2018-01-24T09:12:18+00:00')
    }
)

QboApi::BadRequest: [{
    :fault_type=>"ValidationFault", 
    :error_code=>"2010", 
    :error_message=>"Request has invalid or unsupported property", 
    :error_detail=>"Property Name:2018-01-24 09:10:18 UTC (through reference chain: com.intuit.schema.finance.v3.TimeActivity[\"StartTime\"]) specified is unsupported or invalid"}]
```

I noticed that ActiveSupport already does this by patching the #to_json method for the relevant classes. I was thinking we could fix this without patching the core by working with a #dup of the payload hash, scanning the values for the relevant classes and changing them to ISO 8601 strings before sending the dup'ed payload through JSON.generate. That would only support datetimes in the payload root, though-- otherwise we would need something like ActiveSupport's #deep_dup before doing a recursive replacement. I'd need to double-check if there are any entities with nested datetimes.

Thoughts on implementing?

**Comment by minimul** [comment]
I don't want to get in the business of monitoring and fixing payloads.

The developer should be responsible for the payload and passing in the ISO8601 dates. 

But maybe I'm missing something so feel free to push back.

**Comment by ntippie** [comment]
I have no problem with that, particularly since I'm not seeing a simple and clean implementation. Perhaps we should add something to the README as a warning.

**Comment by minimul** [comment]
Good idea, I will add that to the README when I modify it next but, of course, you starting this thread already gets the info out there.

**Comment by ntippie** [comment]
I was thinking maybe we could use Object#to_json instead of JSON.generate for the payload. That way, if you do have ActiveSupport loaded, it can serialize correctly.

From what I can find, the only difference between the two is that Object#to_json works for many classes, while JSON.generate only accepts Arrays and Hashes.

https://stackoverflow.com/questions/21823995/when-to-use-dump-vs-generate-vs-to-json-and-load-vs-parse-in-rubys-json-lib?lq=1
https://stackoverflow.com/questions/32756039/whats-the-preferred-way-to-dump-a-json-object-to-json-json-generate-or-json-d/32756252

**Comment by minimul** [comment]
Sounds like a clever approach.

How do you propose we do it while not requiring ActiveSupport (not that it would be the end of the world to require ActiveSupport)?

**Comment by ntippie** [comment]
From what I can tell, Object#to_json has been in the Ruby core since 2.0.0. So if we just change JSON.generate(payload) to payload.to_json, it will work almost identically and the DateTime serialization will be fixed if you include ActiveSupport (which edits the to_json method for certain objects). The only difference seems to be that #to_json doesn't raise an error if it receives something other than a Hash or Array.

After including ActiveSupport, you do have to make sure the following two settings are set like so:
```ruby
ActiveSupport::JSON::Encoding.use_standard_json_time_format = true
ActiveSupport::JSON::Encoding.time_precision = 0
```

**Comment by minimul** [comment]
OK. I think this is a worthy improvement.

If you could work up the PR. This would be a new dot release (1.7.0) as well.
