### ISSUE TITLE
application/pdf?

### ISSUE THREAD

**Issue by JohnSmall** [minimul/qbo_api#62]
Using this gem in earnest now. It's really useful and I really appreciate the work you've done on it. I see you've even done a method to get the reports, which is a nice touch. 

But I'm missing a method to get invoices as pdf files. I see from the documentation that it's a simple get request with the invoice id, but I have to set the Content Type = 'application/pdf' and there doesn't seem to be an easy way to do that without adding some extra parameters to the method calls.

Any thoughts?

**Comment by minimul** [comment]
Yeah, a new method would have to be made e.g.
```
qbo_api.get_pdf(:estimate, 3133)
```

**Comment by JohnSmall** [comment]
Ok, I'll do it and send a PR when it's done. It'll be a few days though.

**Comment by minimul** [comment]
Update: @bf4 is going to be adding this ability soon (see comment near bottom => https://github.com/minimul/qbo_api/pull/67)

**Comment by bf4** [comment]
FYI https://github.com/minimul/qbo_api/pull/77

**Comment by minimul** [comment]
Closing as too much time has lapsed.
