### ISSUE TITLE
Weird response from .all(:creditmemo)

### ISSUE THREAD

**Issue by JohnSmall** [minimul/qbo_api#63]
#all(:creditmemo) returns the wrong structure, so the enumerator doesn't work. When I use the API explorer to query "select * from creditmemo" it's got the same structure as other things e.g "select * from invoice" but by the time it percolates up to the enumerator the structure is different so the enumerator just enumerates the outside, not the inner entities. For example;-

This works

    api.all(:bill,max: 1).each{|k| ap k; break}

and returns

    {
            "SalesTermRef" => {
        "value" => "5"
    },
                 "DueDate" => "2018-02-27",
     &etc

I.e the structure of the first entity, as it should be
but this doesn't work

    api.all(:creditmemo,max: 1).each{|k| ap k; break}

and returns this

    [
    [0] "QueryResponse",
    [1] {
           "CreditMemo" => [
            [0] {
                     "RemainingCredit" => 0,
                              "domain" => "QBO",
                              "sparse" => false,
                                  "Id" => "5728",
         &etc

It's returning the outer structure with the entities buried deep inside it.

But when I look at the response from the api explorer 

     select * from bill

returns
     
      {
  "QueryResponse": {
    "Bill": [
      {
        "SalesTermRef": {
          "value": "5"
        },
        "DueDate": "2018-02-27",

And 

      select * from creditmemo

returns

    {
  "QueryResponse": {
    "CreditMemo": [
      {
        "RemainingCredit": 0,
        "domain": "QBO",
        "sparse": false,
        "Id": "5728",

Which is the same structure, Outer "QueryResponse", inner "CreditMemo": which is an array of creditmemos. But somehow this is getting interpreted as an array 

      [
    [0] "QueryResponse",
    [1] {
           "CreditMemo" => [

Reading through the code I can't see any reason why they should be different, and everything else, items, terms, invoices, is OK. It's only with creditmemos that it does weird stuff and there's no line of code `parse_it_wrong if entity == 'creditmemo' `. So I'm mystified.

**Comment by JohnSmall** [comment]
Ahh!!! A clue

     api.query('select * from term MAXRESULTS 1) 

returns
    
     [
    [0] {
             "Name" => "1 Week in arrears",
           "Active" => true,
             "Type" => "STANDARD",

But 

      api.query('select * from paymentmethod MAXRESULTS 1) 

Returns

     {
    "QueryResponse" => {
        "PaymentMethod" => [
            [0] {
                     "Name" => "Adjust",
                   "Active" => true,

But.....

    api.query('select * from PaymentMethod MAXRESULTS 1')

returns

    [
    [0] {
             "Name" => "Adjust",
           "Active" => true,
             
Which is correct. Seeing that parsing the result has to match the exact case of the entity I tried

    api.all('PaymentMethod',max: 1).each{|k| ap k; break}

and got back

    [
    [0] "QueryResponse",
    [1] {
        "PaymentMethod" => [

Which is wrong. So it's something to do with translating the entity names.

**Comment by minimul** [comment]
Thanks. Great find.

**Comment by ntippie** [comment]
I think it might be because you're passing it `:creditmemo` instead of `:credit_memo`, so it translates the entity name to `Creditmemo` instead of `CreditMemo` and can't unwrap the response.
