### ISSUE TITLE
Error in initiatialize and cdc

### ISSUE THREAD

**Issue by odemeulder** [minimul/qbo_api#7]
The following line were giving me issues when trying to run the example:

```
 def initialize(token:, token_secret:, realm_id:, consumer_key: CONSUMER_KEY, 
                 consumer_secret: CONSUMER_SECRET, endpoint: :accounting)
```

I got it to work by changing it as such:

```
 def initialize(token: '', token_secret: '', realm_id: '', consumer_key: CONSUMER_KEY, 
                 consumer_secret: CONSUMER_SECRET, endpoint: :accounting)
```

There were a few more lines with the same issues. Basically passing empty values as default values.

```
cdc ... update ... create ... delete
```

**Comment by minimul** [comment]
Yes, they are required keyword arguments. What use case are you encountering where you don't need to send in those values?

**Comment by odemeulder** [comment]
I followed your tutorial and the app would not run unless I changed that line.

**Comment by minimul** [comment]
I see. Ok, I will take a look. Thanks for the feedback.

**Comment by odemeulder** [comment]
If you want, I'll fork it, try to get it to work on my machine and do a pull request. I've never contributed to OSS, this would be a great first.

**Comment by minimul** [comment]
I would not say there is a bug in the source as those arguments need to be required.

It would be a bug within the tutorials as that is where you got tripped up.

Let me ask: 

- Which tutorial was it exactly?
- and did you properly source the .env file within the console that you ran the example app or specs?

**Comment by odemeulder** [comment]
I got it all to work by upgrading my version of Ruby, as per the requirement (2.2.2). The only hiccup I had was with `index.erb`, I changed the followting setting `payments : true` to `payments : false`
