### ISSUE TITLE
client.authorization_uri doesn't encode ampersands properly in Rails 5?

### ISSUE THREAD

**Issue by joshk6** [minimul/qbo_api#75]
Hi there.  I was able to get your example up and running just fine, but when I ported the code into my own rails project I run up against an error trying to authenticate with oauth 2.

The url produced in the connect to quickbooks button produced in the eample app looks like this:

`https://appcenter.intuit.com/connect/oauth2client_id=Q0tvAA[...]&response_type=code&scope=com.intuit.quickbooks.accounting&state=bdafa[...] 
`
This works fine and gets me to the authentication page.

The url using the same code as in your example in my rails app looks like this:

`https://appcenter.intuit.com/connect/oauth2client_id=Q0tvAA&amp;response_type=code&amp;scope=com.intuit.quickbooks.account`

this doesn't work and brings up an error page saying the "The response_type query parameter is missing from the authorization request".

My assumption is because insteadd of coding &response=... in the url it is encoding 

> & amp;response=

... How to fix this?

Many thanks.

**Comment by minimul** [comment]
Post your view code for generating the URL.

**Comment by joshk6** [comment]
Code is as follows:  

login.html.rb

```
<h1>QboController#login</h1>
<p>Find me in app/views/qb_controller/login.html.erb</p>

<script type="text/javascript" src="<%= QboApi::APP_CENTER_BASE %>/Content/IA/intuit.ipp.anywhere-1.3.1.js"></script>
<script>
    <% @uri = @client.authorization_uri(scope: 'com.intuit.quickbooks.account', state: session[:state]) %>
    <% puts @uri %>
    <% puts "State: #{session[:state]}" %>
    intuit.ipp.anywhere.setup({
        grantUrl: "<%= @uri %>",
        datasources: {
            quickbooks : true,
            payments : false
        }
    });
</script>


<ipp:connectToIntuit></ipp:connectToIntuit>
```

Here is the value that is puts'd out on the counsole when the page is loaded:

https://appcenter.intuit.com/connect/oauth2?client_id=Q0tvAAMFxrCfnhJysKjX9oVlKt8NOYo1iB1wFGYhDDvMmWyB9n&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-redirect&response_type=code&scope=com.intuit.quickbooks.account&state=0b009843-7d33-42d2-9f4b-7b051f1c5abc

The connect to quickbooks button is rendered normally. When the button is clicked, here is the URL that new browswer window tries to connect to: 

https://appcenter.intuit.com/connect/oauth2?client_id=Q0tvAAMFxrCfnhJysKjX9oVlKt8NOYo1iB1wFGYhDDvMmWyB9n&amp;redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-redirect&amp;response_type=code&amp;scope=com.intuit.quickbooks.account&amp;state=0b009843-7d33-42d2-9f4b-7b051f1c5abc

The page result shows 

> We're sorry!  The response_type query parameter is missing from the authorization request.  Click here to learn more about authorization requests and associated query parameters.

Interestingly if you click on the link in the console output, it appears to connect , except I think some data that should be in the request is missing if you just try to GET the uri.

The redirect url is called, but param[:error] comes back with "invalid_scope".

**Comment by minimul** [comment]
Try the double equals `==` e.g.
```
 grantUrl: "<%== @uri %>
```

**Comment by joshk6** [comment]
That did it.  Many thanks.

**Comment by minimul** [comment]
Update: @bf4 is going to be adding this ability soon (see comment near bottom => https://github.com/minimul/qbo_api/pull/67)
