### ISSUE TITLE
How to avoid spawning another browser session on login?

### ISSUE THREAD

**Issue by joshk6** [minimul/qbo_api#78]
Hi, in your example app, when you press the quickbooks button it opens a new browser window in chrome, and the redirect url back to my app is called in this now window,  rather than on the page where the button is located. Also the new window has the address bar blocked from takiing focus 

  Is there a way to alter this behavior so that the redirect happens on the page where my button is located?  I guess its OK tha thte authentication process spawns a new window (which I could have close) but it is a little confusing if the app continues running in the new browser window on redirect rather than the window where the button was originally pressed.  
Thanks.

**Comment by minimul** [comment]
See my answer [here](https://github.com/ruckus/quickbooks-ruby/issues/382).

**Comment by joshk6** [comment]
Thanks, that javascript part did the trick.
