### ISSUE TITLE
Create methods not working

### ISSUE THREAD

**Issue by xrimpy** [minimul/qbo_api#79]
I can successfully fetch data from the API. 
The following work as expected

I have made a custom class to store HashKey

qboapi = QboApi.new( access_token: HashKey.fetch( 'QUICKBOOKS_ACCESS' ), realm_id: HashKey.fetch( 'QUICKBOOKS_REALM_ID' ) )

qboapi.get :customer, 1
order = Order.last

Having problems creating entries. 

The same payload works if I try it on PostMan

data = '{
"BillAddr": {
"Line1": "123 Main Street",
"City": "Mountain View",
"Country": "USA",
"CountrySubDivisionCode": "CA",
"PostalCode": "94042"
},
"Notes": "Here are other details.",
"DisplayName": "King Groceries1",
"PrimaryPhone": {
"FreeFormNumber": "(555) 555-5555"
},
"PrimaryEmailAddr": {
"Address": "jdrew@myemail.com"
}
}'

qboapi.create(:customer, payload: data)

The is the error

[{:fault_type=>"ValidationFault", :error_code=>"500", :error_message=>"Unsupported Operation", :error_detail=>"Operation Could not find resource for relative : /v3/company/193514733709249/customer of full path: https://sandbox.qbo.intuit.com/qbo51/v3/company/193514733709249/customer is not supported."}]

**Comment by minimul** [comment]
@xrimpy Post the full transaction log

**Comment by minimul** [comment]
Need to turn on logging. See README under configuration options.

**Comment by minimul** [comment]
@bf4 Are you guys running v1.8.1?

**Comment by mpipkorn** [comment]
I am.  qbo_api 1.8.1, oauth 0.5.4, simple_oauth 0.3.1 (both are required), faraday 0.14.0

**Comment by minimul** [comment]
@mpipkorn @xrimpy I am able to reproduce this. Working on it now.

**Comment by mpipkorn** [comment]
Tried backing out the qbo_api gem version (all other gems stayed the same).
1.8.0 gives the same error
1.7.1 works fine!!!

**Comment by minimul** [comment]
@mpipkorn @xrimpy 
Version 1.8.2 fixes this. Sorry this bug wasted time for you all (and others I'm sure).

**Comment by bf4** [comment]
I introduced that. Sorry. weird that I wasn't haven't that issue.

**Comment by minimul** [comment]
@bf4 Not your fault at all. 

The buck stops with me. 

All those changes and I didn't even run any live requests before publishing those releases.

**Comment by bf4** [comment]
I find it helpful to write up release steps. I agree that updating the cassettes should be the last step before release.

**Comment by xrimpy** [comment]
Cheers for the swift reply @minimul 

Problem is resolved, and we have rolled out our App.

Thank you
