### ISSUE TITLE
OAuth 2.0 requests returning 401 Unauthorized

### ISSUE THREAD

**Issue by virtuexru** [minimul/qbo_api#84]
I'm trying to create a connection to QBO via OAuth 2.0 example you guys have. I get the access token & refresh token then create a connection like so:

`api = QboApi.new(access_token: session[:access_token], realm_id: session[:realm_id])`

Then making a call like:

`api.get :customer, 58`

returns me an authentication error:

```
AuthenticationErrorGeneral: SRV-110-Authentication Failure , statusCode: 401
```

Even though I can make this exact same call from their API Explorer (yes I've double and triple checked the URL's/Realm ID). I've also double checked the API keys from the settings page and everything matches. It's very strange that I get a proper access token but can make no subsequent calls.

I am using this example:

[https://github.com/minimul/qbo_api/blob/master/example/oauth2.rb](https://github.com/minimul/qbo_api/blob/master/example/oauth2.rb)

Any help? Anyone else able to make OAuth 2.0 calls successfully? (This is for development sandbox)

**Comment by virtuexru** [comment]
@minimul I appreciate you helping me out. Still getting the same error; I'm convinced I've missed something straightforward but can't figure out what.

```
I, [2018-04-12T10:49:58.996523 #10825]  INFO -- : [[QuickBooks]] GET https://sandbox-quickbooks.api.intuit.com/v3/company/193514000000000/customer/58
D, [2018-04-12T10:49:58.996623 #10825] DEBUG -- : [[QuickBooks]] "Accept: application/json\nContent-Type: application/json;charset=UTF-8\nUser-Agent: Faraday v0.9.0\n\n"
E, [2018-04-12T10:49:59.900271 #10825] ERROR -- : QboApi::Unauthorized - [{:fault_type=>"AuthenticationFault", :error_code=>"100", :error_message=>"General Authentication Error", :error_detail=>"AuthenticationErrorGeneral: SRV-110-Authentication Failure , statusCode: 401"}] (/Users/x/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/qbo_api-1.8.3/lib/qbo_api/raise_http_exception.rb:15:in `block in call')
QboApi::Unauthorized: [{:fault_type=>"AuthenticationFault", :error_code=>"100", :error_message=>"General Authentication Error", :error_detail=>"AuthenticationErrorGeneral: SRV-110-Authentication Failure , statusCode: 401"}]
from /Users/x/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/qbo_api-1.8.3/lib/qbo_api/raise_http_exception.rb:15:in `block in call'
```

I've confirmed the realm_id (aka the company id) and URL matches what I'm doing in API explorer. I've double checked the QB CLIENT key + secret. I'm receiving a proper `access_token` & `refresh_token` after doing `resp = client.access_token!` But every call afterward with `QboApi.new` -> `.get` fails.

**Comment by bf4** [comment]
Possibly dumb question, but are you using the authentication flow first to get the authorization_code and exchange that for the access token and refresh token?

- Get authorization code  https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app#Refreshing_the_access_token
- Exchange authorization code for refresh and access tokens https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app#Exchange_code_for_refresh_and_access_tokens

Were you able to get a customer using the example app?

**Comment by ntippie** [comment]
https://developer.intuit.com/docs/00_quickbooks_online/2_build/10_authentication_and_authorization/10_oauth_2.0

Look at the examples there and make sure you indeed have the access token. It's much longer than the other tokens passed around during OAuth2.

Also, ensure that the client ID and client secret are both being read properly by the example.

**Comment by virtuexru** [comment]
Thank you for all the replies @minimul @bf4 @ntippie. I ran the Sinatra example and it works fine. I get the same length/type of access/refresh tokens that I do on my app with rails; still not sure what the issue is because once I call the API using:

```
api = QboApi.new(access_token: access_token, realm_id: session[:realmId])
@resp = api.get :customer, 50
```

I'm getting the same error (`SRV-110-Authentication Failure , statusCode: 401`) meanwhile the Sinatra app is being called fine. I'm also using the same env variables for the `QBO_API_CLIENT_ID` & `QBO_API_CLIENT_ID`. Is anyone else running this on rails or just sinatra? Maybe I'm missing some kind of setup outside of the controller work

**Comment by bf4** [comment]
@virtuexru 

1. Get your access token. (not authentication token or auth code or refresh token).  *make sure there are no line breaks in it*.
2. Get your realm id/ company id

Edit the first two lines then run this and share. I've tested these and they work.

```bash
access_token="put the access token in these quotes"
realm_id="put the company id in these quotes"
cat <<EOF > qbo_api_test.rb
require 'bundler/inline'

install_gems = true
gemfile(install_gems) do
  source 'https://rubygems.org'

  gem 'qbo_api'
end

require 'qbo_api'

QboApi.log = true
api = QboApi.new(access_token: "${access_token}", realm_id: "${realm_id}")
p api.get :company_info, "${realm_id}"
EOF
ruby qbo_api_test.rb
```

If that doesn't work, can you try just making a request in postman or with curl?

```bash
access_token="put the access token in these quotes"
realm_id="put the company id in these quotes"
curl -X GET "https://sandbox-quickbooks.api.intuit.com/v3/company/${realm_id}/companyinfo/${realm_id}" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json;charset=UTF-8" \
 -H "User-Agent: virtuexru  test" \
 -H "Authorization: Bearer ${access_token}"
```

**Comment by virtuexru** [comment]
@bf4 

Thanks for the response. Same issue (Sinatra access_token works, Rails does not). The postman response to the access_token I get from the Sinatra app gives me the proper customer object, the Rails app gives me:

```
{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthenticationFailed; errorCode=003200; statusCode=401","detail":"","code":"3200","element":null}],"type":"AUTHENTICATION"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1524495489389,"status":null,"cdcresponse":[]}%
```

The only real difference I can see (besides some dependency) is that I'm going through the flow on Sinatra via the Javascript button whereas on Rails I'm using:

`oauth2_client.authorization_uri`

**Comment by bf4** [comment]
@virtuexru 
> I've narrowed down that this is basically a Rails problem. I
If my 'Rails' you mean your app.  Did you try the snippets I gave you? I took the time to write them and confirm them.  I run a Rails app using OAuth2 and I don't have this problem. Those snippets have no dependencies, so it would be helpful.

Now, it sounds like you have some oauth2_client. It could be a config there. Who knows. I don't use the javascript in the example app. I use the flow described by intuit without any oauth2 client. But that's not Rails, that's your app.

I'm not really sure how to get you to share what your'e doing in a way we can reproduce it. Until you do, I can't help.   You're not the only person using the gem in Rails, so it might not be the gem.

**Comment by virtuexru** [comment]
@bf4 yes sorry I should've been more specific; by Rails I meant our Rails app & its dependancies. I appreciate you taking the time out to write those snippets; they do work (depending on what app I use to get the initial access_token [sinatra example vs my rails app]). I'm going to close this issue now as it is not a QboApi specific problem. I appreciate all the help!

**Comment by bf4** [comment]
@virtuexru Why don't you share you oauth2 client config? My money is that's where the problem is

**Comment by rikkipitt** [comment]
@virtuexru did you get to the bottom of your Rails issue? I'm having the same problem - CURL works, but in a Rails app, it fails as above...

Cheers!

**Comment by minimul** [comment]
Thanks @rikkipitt

**Comment by sedhha** [comment]
Can somebody explain the correct procedure guys? I am still struggling in 2021 to make the correct request.

**Comment by minimul** [comment]
@sedhha Need to provide very specific details if you're going to get any help.
