### ISSUE TITLE
Tax code issues

### ISSUE THREAD

**Issue by viveki2it** [minimul/qbo_api#85]
Hi,

I'm using this gem to integrate quickbooks with my product. I'm able to sync invoice and it's line items to quickbooks and I've also figured out a way that how to apply tax code on invoice line items but I'm facing an issue when I try to apply tax rate to a quickbooks invoice. Can anyone please guide me to some tutorial or help me by telling me about what methods I should use to apply the tax-rate. 

And alo, let me know there is a way to integrate custom taxes to invoices.

Thanks.

**Comment by minimul** [comment]
Have you read through this [tutorial](https://developer.intuit.com/docs/00_quickbooks_online/2_build/60_tutorials/0020_create_an_invoice)?

**Comment by ntippie** [comment]
Applying a tax code to an sales transaction is done at the transaction level for companies that use the global QBO edition, and at the transaction line level for companies that use the US QBO edition. As I recall, you can't use both methods in the same company with the v3 API. You can tell which method you should be following for a given company by querying the CompanyInfo resource for the Country attribute.

```ruby
line_level_tax = qbo_api.get(:company_info, qbo_api.realm_id)['Country'] != 'US'
```

**Comment by bf4** [comment]
@viveki2it You may find my notes in https://github.com/minimul/qbo_api/pull/77#discussion_r177903418 helpful
