### ISSUE TITLE
QboApi::COMSUMER_KEY and QboApi::CONSUMER_SECRET not being read as defaults

### ISSUE THREAD

**Issue by ntippie** [minimul/qbo_api#87]
The method inheritance for `QboApi::Connection::OAuth1#default_attributes` isn't working, since included modules don't supersede or overwrite existing methods. I have a commit coming shortly that will fix this by using `prepend Connection` instead of `include Connection`, but also want to throw it over to @bf4 in case you want to solve it in another manner.

**Comment by bf4** [comment]
Looking at

https://github.com/minimul/qbo_api/blob/v1.8.3/lib/qbo_api/connection/oauth1.rb#L16-L22

and

https://github.com/minimul/qbo_api/blob/v1.8.3/lib/qbo_api/connection.rb#L132-L135

I had thought I separated the code but didn't change the behavior of default attributes. I thought I tested this too but maybe not having an oauth1 connection available is why I missed it. Can you record a failing test maybe?

until then, it's simple enough to pass in the variables yourself.

Does that mean https://github.com/minimul/qbo_api/blob/v1.8.3/example/oauth.rb#L20-L21 doesn't work for you? Again, I was unable to test it, but that's how I might debug it

**Comment by minimul** [comment]
No longer relevant. FYI. I just [pushed a branch](https://github.com/minimul/qbo_api/tree/2_0_0) that among other things, rips out all OAuth1 code. Will be released soon as 2.0.0.
