### ISSUE TITLE
"Get" seems to be throwing a debug notification?

### ISSUE THREAD

**Issue by joshk6** [minimul/qbo_api#92]
When I execute a get request for a purchase order, I'm getting the following in my console.
I didn't write it so I'm guessing its coming from the gem somewhere?

It looks like what's happening is that entity_name is set to "Purchaseorder" instead of "PurchaseOrder"?

D, [2018-10-09T10:39:45.808334 #74262] DEBUG -- : [QuickBooks] entity name not in response body: entity="PurchaseOrder" entity_name="Purchaseorder" body={"PurchaseOrder"=>{"ShipAddr"=>

**Comment by minimul** [comment]
I suspect you're doing:
`qbo_api.get :purchaseorder, 100`

Needs to be snake case:

`qbo_api.get :purchase_order, 100`
