### ISSUE TITLE
How to update preferences?

### ISSUE THREAD

**Issue by jonewalt** [minimul/qbo_api#95]
I keep getting a 10000 system level error when I try this:

`qbo_api.update(:preferences, id: "", payload: preferences)`

or a method failure when I omit the `id`.  

Any help updating `Preferences` as well as any other `supporting_entities` would be amazing, thanks!

**Comment by minimul** [comment]
Only a small subset of preference resource attributes are updatable so you are most likely running up against that.

See the biz rules for the [preference resource](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/preferences).

**Comment by jonewalt** [comment]
I started sending the full response back (with needed changes), and that's working - must have dropped something necessary in the payload.  Thanks!
