### ISSUE TITLE
Recurring invoices

### ISSUE THREAD

**Issue by itaisoudry** [minimul/qbo_api#99]
I had a thought about recurring invoices (invoice every month).
Since there is no recurring invoice in the API, I was thinking about implementing a function (using qbo API) that gets a list of customers, extract the last sent invoice, and if month has passed, send a new one.

What do you think?
I'm thinking about implementing it my self. 

I'm not an experienced Ruby developer, but I would like to try.

**Comment by minimul** [comment]
@itaisoudry Thanks for the suggestion.

I would consider recurring invoice support out of scope for qbo_api but I think the idea would be perfect for a stand-alone gem.
